### ISSUE TITLE
"Possibly misspelt word 'fromkeys'" error shouldn't be showing up 

### ISSUE THREAD

**Issue by ekhudikova** [hyperskill/hyperstyle#100]
One of our users pointed out this error:

1. Open https://hyperskill.org/learn/step/11104
2. Submit the following code:

```
# the list with classes; please, do not modify it
groups = ['1A', '1B', '1C', '2A', '2B', '2C', '3A', '3B', '3C']

kg_dict = dict.fromkeys(groups, None)
for i in range(int(input())):
    kg_dict[groups[i]] = int(input())
print(kg_dict)
```

The code style error Possibly misspelt word 'fromkeys' shouldn't be showing up.
This bug appeared for the first time on production (main branch) about a month ago (23 days ago).

**Comment by nbirillo** [comment]
@GirZ0n also please add some words from plotly:
yanchor
yaxes
xanchor
xaxes
showline
linewidth
linecolor
bgcolor
barmode
