### ISSUE TITLE
'CLASS_DEF' should be separated from the previous line -  shouldn't be showing up

### ISSUE THREAD

**Issue by darya-andreyeva** [hyperskill/hyperstyle#138]
1. Open: https://hyperskill.org/learn/step/3007
2. Submit:
```
 class Phone {

    String ownerName;
    String countryCode;
    String cityCode;
    String number;

    public Phone(String ownerName, String number) {
        this.ownerName = ownerName;
        this.number = number;
    }

    public Phone(String ownerName, String countryCode, String cityCode, String number) {
        this.ownerName = ownerName;
        this.countryCode = countryCode;
        this.cityCode = cityCode;
        this.number = number;
    }
}
```
Shows code style error "CLASS_DEF' should be separated from the previous line" when the solution starts from the first line
The problem appeared recently

**Comment by nbirillo** [comment]
@darya-andreyeva I got another one - `'class def ident' has incorrect indentation level 1, expected level should be 0.`
Which version of the hyperstyle do you use?

My issue is ok since you have a space before keyword **class** and it is a formatting issue

**Comment by nbirillo** [comment]
Could you please check if this task has a hidden template? Since the hyperstyle tool can not find this error if the file start from this class

**Comment by nbirillo** [comment]
I have checked it and this task probably has  hidden template
since if I use thick code:
```

class Phone {

    String ownerName;
    String countryCode;
    String cityCode;
    String number;

    public Phone(String ownerName, String number) {
        this.ownerName = ownerName;
        this.number = number;
    }

    public Phone(String ownerName, String countryCode, String cityCode, String number) {
        this.ownerName = ownerName;
        this.countryCode = countryCode;
        this.cityCode = cityCode;
        this.number = number;
    }
}
```
everything works fine. Probably you should add one new line in the template

**Comment by vyahhi** [comment]
@ksezha-dz if we disable this, then users won't get a valuable feedback for some other problems where it's appropriate.

>I believe that there might be multiple tasks that now have this check but that's time-consuming to search for them manually. 

But we can find it automatically.

> Also, changing the templates doesn't guarantee that the settings won't be changed again in the future. 

Agree. 
I think it would be awesome to monitor the most common code style errors which users receive in each problem, and if some problems have a high number of identical style errors, then these problems should be updated.

**Comment by nbirillo** [comment]
@ksezha-dz I will think about how we can add monitoring for issues and discuss it with @vyahhi  later

**Comment by ksezha-dz** [comment]
@nbirillo okay, thank you! We would like to add that there are other checks that we'd like to skip, that are:

- **"Serializable" classes should have a "serialVersionUID"**
- **MagicNumberCheck**

Also, the following settings might be annoying when creating simple tasks:

```
class A { }

class B extends A {
    private int b;

    B(int b) {
        this.b = b;
    }
}
```
produces **[CallSuperInConstructor] It is a good practice to call super() in a constructor.**
Since the checker cannot know whether we really need to call super, it warns us just in case.

And the bug mentioned in the issue still persists:

```
::java17
::header
import java.util.*;

::code

class A { }
```
produces **[EmptyLineSeparatorCheck] 'CLASS_DEF' should be separated from previous line.**

**Comment by nbirillo** [comment]
@ksezha-dz **MagicNumberCheck** is INFO issue and does not influence the final grade. Should we disable it? I am not sure.... @vyahhi what do you think?

About **serialVersionUID** - I will disable it

**CallSuperInConstructor** is a best practice issue and in general, it is a useful issue for students. Moreover, this issue has medium difficulty and to my knowledge, in the future students will be able to choose the level of the code quality inspections. @vyahhi isn't?


About **EmptyLineSeparatorCheck** - could you please send a step example with this bag? Is it only for java17, right?

**Comment by ksezha-dz** [comment]
@nbirillo here's the problem that contains this bug: https://hyperskill.org/learn/step/12441
> About EmptyLineSeparatorCheck - could you please send a step example with this bag? Is it only for java17, right?

This issue can be reproduced in Java 11, so it's not Java 17 specific

**Comment by GirZ0n** [comment]
This problem is related to the creation of a file with the student's solution from the template on the platform. Therefore, we cannot fix it.
