### ISSUE TITLE
AbstractClassWithoutAbstractMethod turn off issues

### ISSUE THREAD

**Issue by tiginamaria** [hyperskill/hyperstyle#151]
Content managers of the course ask to turn off **AbstractClassWithoutAbstractMethod** issue because it is normal for them to use abstract class without abstract methods (like in step https://hyperskill.org/learn/step/5768).

**Comment by GirZ0n** [comment]
Fixed in [6c8d506](https://github.com/hyperskill/hyperstyle/commit/6c8d506cb845de906355e7c8e4e116e3617ac9e7).
