### ISSUE TITLE
Spellchecker error

### ISSUE THREAD

**Issue by Y-ulia-A** [hyperskill/hyperstyle#153]
The linter throws a 'possibly misspelt word' error for a perfectly fine 'Lightbulb'.
Step link: https://hyperskill.org/learn/step/6988
The users [are not happy](https://hyperskill.org/learn/step/6988#comment-1034915) : /

<img width="991" alt="Screenshot 2022-07-15 at 11 31 45" src="https://user-images.githubusercontent.com/91261377/179174925-ced88a2c-0daf-4c70-8b10-f7291f0cc258.png">

**Comment by nbirillo** [comment]
@GirZ0n could you please check it?

**Comment by GirZ0n** [comment]
Fixed in 46a5e289bc82a24565c85efc8c72ba5bb7b4d3e9.
