### ISSUE TITLE
LanguageVersion.JAVA_17 enum

### ISSUE THREAD

**Issue by tiginamaria** [hyperskill/hyperstyle#159]
It would be great if you add JAVA_17 = 'java17' to LanguageVersion enum class https://github.com/hyperskill/hyperstyle/blob/e10a38c40e1195b12e0af02285163755265731bd/hyperstyle/src/python/review/application_config.py#L24-L32
In the hyperskill platform java17 is already induced and I need it for new platform code templates analysis.

**Comment by nbirillo** [comment]
@GirZ0n could you please resolve this issue?
