### ISSUE TITLE
Incorrect indentations if a code snippet contains hidden templates

### ISSUE THREAD

**Issue by swsms** [hyperskill/hyperstyle#64]
If there are hidden templates which conceal classes/methods, the tool shows us a lot of warnings.
May be it should be modified somehow.
![Screenshot 2021-07-18 at 20 15 30](https://user-images.githubusercontent.com/16266572/126072574-435da576-b68a-448f-ac56-39742b8569b0.png)

![Screenshot 2021-07-18 at 20 18 45](https://user-images.githubusercontent.com/16266572/126072610-ccdb234d-ed2f-43b3-ad25-93fc5e5a8470.png)

May be it is worth filtering such kind of warnings if code has the start and end line borders.

**Comment by vyahhi** [comment]
We probably should just skip the code quality pipeline on problems with hidden templates.
