### ISSUE TITLE
"Possibly misspelt word: 'sqrt'" <- it shouldn't be showing up.

### ISSUE THREAD

**Issue by vyahhi** [hyperskill/hyperstyle#67]
1. Open https://hyperskill.org/learn/step/6346
2. Submit the following code:

```
import math
a = float(input())
area = 2 * math.sqrt(3.0) * pow(a, 2)
volume = 1.0 / 3.0 * math.sqrt(2) * pow(a, 3)
```

The code style error `Possibly misspelt word: 'sqrt'` shouldn't be showing up.

This bug appeared on production (`main` branch) in the recent update.

**Comment by nbirillo** [comment]
Closed according to [PR#68](https://github.com/hyperskill/hyperstyle/pull/68)
